services:

  # Container with Postgresql database
  postgresql:
    image: postgres:16-alpine
    container_name: postgresql
    restart: unless-stopped
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data    
    networks:
      - internal-net  
    env_file: 
      - '.env'      

  # Container with redis database for cash
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_HOST_PASSWORD}"]  # set the password from '.env' file
    networks:
      - internal-net
    env_file: 
      - '.env'      

  # Container with main nextcloud application
  app:
    build: .
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./nextcloud:/var/www/html
    env_file:
      - '.env'
    networks:
      - internal-net  

  # Container with cron task, which is needed for main nextcloud container. It's better to divide cron from main nextcloud container.
  cron:
    image: nextcloud:fpm
    container_name: nextcloud-cron
    restart: unless-stopped
    depends_on:
     - app
     - postgresql
     - redis    
    volumes:
      - ./nextcloud:/var/www/html
    entrypoint: /cron.sh
    env_file:
      - '.env'
    networks:
      - internal-net

  # Container with nginx which serves as web for nextcloud
  web:
    image: nginx:alpine
    container_name: nextcloud-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - '8080:80'      
      - '8843:443'
    volumes:
      - ./nextcloud/:/var/www/html:ro
      - ./nginx/nextcloud.conf:/etc/nginx/nginx.conf:ro  
    networks:
      - internal-net  

  # Reverse proxy for redirection
  proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - '80:80'      
      - '443:443'
    volumes:
      - ./nginx-reverse-proxy/reverse.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-reverse-proxy/certs:/etc/nginx/certs:ro
      - ./nginx-reverse-proxy/snippets:/etc/nginx/snippets:ro
    networks:
      - internal-net  
 
  # Container with portainer
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - '9000:9000'            
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    networks:
      - internal-net    

  authelia:
    image: authelia/authelia:latest
    container_name: authelia    
    restart: unless-stopped
    ports:
      - '9091:9091'
    volumes:
      - ./authelia/:/config/  
    networks:
      - internal-net  
    environment:
      AUTHELIA_JWT_SECRET_FILE: /config/secrets/jwt_secret.txt     
      AUTHELIA_SESSION_SECRET_FILE: /config/secrets/session_secret.txt
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /config/secrets/storage_key.txt
      SSL_CERT_FILE: /config/secrets/TCONET-CA.crt
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /config/secrets/ldap_pass.txt
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE: /config/secrets/oidc.key
    depends_on:
      - "redis" 
    extra_hosts:
      - "kos-authelia.intern.tconet.de:192.168.0.40"   

networks:
  internal-net:
    driver: bridge

    