location = /authelia {
    internal;
    proxy_pass                              http://authelia:9091/api/verify;      # Authelia verification endpoint
    proxy_set_header Host                   $host;
    proxy_set_header X-Original-URL         $scheme://$http_host$request_uri;
    proxy_set_header X-Forwarded-Proto      $scheme;
    proxy_set_header X-Forwarded-Host       $http_host;
    proxy_set_header X-Forwarded-URI        $request_uri;
    proxy_set_header X-Forwarded-For        $remote_addr;
    proxy_set_header Content-Length "";
    proxy_pass_request_body off;                     
}


# if not authorized, send request to authorized portal
error_page 401 =302 https://kos-authelia.intern.tconet.de/?rd=$scheme://$host$request_uri;