[req]
default_bits       = 4096
distinguished_name = req_distinguished_name
req_extensions     = v3_req
prompt             = no

[req_distinguished_name]
CN = kos-nextcloud.intern.tconet.de

[v3_req]
subjectAltName = @alt_names

[alt_names]
DNS.1 = kos-nextcloud.intern.tconet.de
DNS.2 = kos-portainer.intern.tconet.de
DNS.3 = kos-authelia.intern.tconet.de

